import type { BootstrapPayload } from '../context/DataContext';

// Готовая демонстрационная сцена для тестового режима эксперта:
// полный жизненный цикл задач уже пройден, эксперту остаётся только смотреть
// и при желании попробовать самому.

const ORG_NAME = 'Центральная библиотека г. Кстово';

const daysFromNow = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(12, 0, 0, 0);
  return date.toISOString();
};

const daysAgo = (days: number): string => daysFromNow(-days);

const buildTask = (overrides: Partial<BootstrapPayload['tasks'][number]>): BootstrapPayload['tasks'][number] => ({
  id: '',
  slug: '',
  title: '',
  description: '',
  requirements: '',
  organizationId: 'expert-organization',
  organizationName: ORG_NAME,
  category: 'Веб-разработка',
  format: 'online',
  workload: 'one_day',
  taskType: 'website',
  urgency: 'normal',
  requiresOrgMaterials: true,
  requiresOnsiteCheck: false,
  pointsReward: 100,
  pointsMin: 90,
  pointsRecommended: 100,
  pointsMax: 120,
  pointsExplanation: ['Базовая ставка пилота: 80–140 баллов в зависимости от объёма'],
  taskKind: 'single',
  childOrder: 0,
  subtaskCount: 0,
  completedSubtaskCount: 0,
  siblingCount: 0,
  deadline: daysFromNow(14),
  status: 'open',
  createdAt: daysAgo(21),
  attachments: [],
  ...overrides,
});

const buildMember = (
  responseId: string,
  taskId: string,
  studentId: string,
  studentName: string,
  role: 'leader' | 'member',
): BootstrapPayload['responses'][number]['teamMembers'][number] => ({
  id: `demo-member-${studentId}-${taskId}`,
  responseId,
  taskId,
  studentId,
  studentName,
  role,
  university: 'Университет Неймарк',
  course: 2,
  skills: [],
  createdAt: daysAgo(18),
});

const buildResponse = (
  overrides: Partial<BootstrapPayload['responses'][number]>,
): BootstrapPayload['responses'][number] => ({
  id: '',
  taskId: '',
  studentId: '',
  studentName: '',
  status: 'accepted',
  coverLetter: '',
  appealCount: 0,
  createdAt: daysAgo(18),
  updatedAt: daysAgo(10),
  teamMembers: [],
  ...overrides,
});

export const buildExpertDemoState = (): BootstrapPayload => ({
  tasks: [
    buildTask({
      id: 'demo-task-announce',
      slug: 'demo-task-announce',
      title: 'Анонс фестиваля «Лето в парке» для соцсетей',
      description: 'Нужна серия из трёх картинок и текст для публикаций о летнем фестивале в городском парке.',
      requirements: 'Формат 1080×1080, единый стиль, тексты на русском. Используйте фото из архива библиотеки.',
      category: 'Копирайтинг и SMM',
      taskType: 'content',
      pointsReward: 85,
      pointsMin: 75,
      pointsRecommended: 85,
      pointsMax: 105,
      deadline: daysFromNow(10),
      status: 'open',
      createdAt: daysAgo(3),
    }),
    buildTask({
      id: 'demo-task-form',
      slug: 'demo-task-form',
      title: 'Форма онлайн-записи в библиотеку',
      description: 'Читатели просят записываться на мероприятия онлайн. Нужна простая форма записи с подтверждением.',
      requirements: 'Имя, контакт, выбранное мероприятие. После отправки — экран благодарности.',
      category: 'Веб-разработка',
      taskType: 'website',
      pointsReward: 90,
      pointsMin: 80,
      pointsRecommended: 90,
      pointsMax: 110,
      deadline: daysFromNow(6),
      status: 'review',
      createdAt: daysAgo(14),
    }),
    buildTask({
      id: 'demo-task-landing',
      slug: 'demo-task-landing',
      title: 'Лендинг выставки «Кружевные истории»',
      description: 'Одна страница-презентация выставки кружева: история, экспонаты, время работы.',
      requirements: 'Адаптивная вёрстка, галерея из 6 экспонатов, карта с проездом.',
      category: 'Дизайн и UX',
      taskType: 'design',
      pointsReward: 110,
      pointsMin: 100,
      pointsRecommended: 110,
      pointsMax: 130,
      deadline: daysFromNow(12),
      status: 'in_progress',
      executorId: 'sp-demo-alina',
      createdAt: daysAgo(12),
    }),
    buildTask({
      id: 'demo-task-poster',
      slug: 'demo-task-poster',
      title: 'Афиша летней программы чтения',
      description: 'Яркая афиша для печати и соцсетей: летняя программа чтения для детей.',
      requirements: 'A3 для печати и квадрат для VK. Стиль — лето, книги, дети.',
      category: 'Дизайн и UX',
      taskType: 'design',
      pointsReward: 105,
      pointsMin: 95,
      pointsRecommended: 105,
      pointsMax: 125,
      deadline: daysAgo(4),
      status: 'completed',
      executorId: 'expert-student',
      createdAt: daysAgo(20),
    }),
    buildTask({
      id: 'demo-task-archive',
      slug: 'demo-task-archive',
      title: 'Страница цифрового архива районной газеты',
      description: 'Собрать страницу архива выпусков районной газеты с поиском по годам.',
      requirements: 'Хронология выпусков, поиск по году, адаптив под телефон.',
      category: 'Веб-разработка',
      taskType: 'website',
      pointsReward: 140,
      pointsMin: 130,
      pointsRecommended: 140,
      pointsMax: 160,
      deadline: daysAgo(2),
      status: 'completed',
      executorId: 'sp-demo-gleb',
      createdAt: daysAgo(25),
    }),
  ],
  responses: [
    buildResponse({
      id: 'demo-response-landing',
      taskId: 'demo-task-landing',
      studentId: 'sp-demo-alina',
      studentName: 'Яруллина Алина',
      status: 'accepted',
      coverLetter: 'Сделаю лендинг в Figma и сверстаю: есть опыт выставочных страниц.',
      teamMembers: [
        buildMember('demo-response-landing', 'demo-task-landing', 'sp-demo-alina', 'Яруллина Алина', 'leader'),
        buildMember('demo-response-landing', 'demo-task-landing', 'sp-demo-magomed', 'Гаджиев Магомедрасул', 'member'),
        buildMember('demo-response-landing', 'demo-task-landing', 'expert-student', 'Эксперт Тестовый', 'member'),
      ],
    }),
    buildResponse({
      id: 'demo-response-form',
      taskId: 'demo-task-form',
      studentId: 'sp-demo-viktoria',
      studentName: 'Пак Виктория',
      status: 'submitted',
      coverLetter: 'Готова сделать форму за два дня.',
      submissionLink: 'https://demo.stud-pod.local/forma-zapisi',
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
      teamMembers: [
        buildMember('demo-response-form', 'demo-task-form', 'sp-demo-viktoria', 'Пак Виктория', 'leader'),
      ],
    }),
    buildResponse({
      id: 'demo-response-poster',
      taskId: 'demo-task-poster',
      studentId: 'expert-student',
      studentName: 'Эксперт Тестовый',
      status: 'completed',
      coverLetter: 'Сделаю афишу за три дня, есть опыт печатного дизайна.',
      submissionLink: 'https://demo.stud-pod.local/afisha-letnej-programmy',
      reviewComment: 'Принято! Яркая афиша, всё по техническому заданию. Начислено 105 баллов.',
      createdAt: daysAgo(19),
      updatedAt: daysAgo(4),
      teamMembers: [
        buildMember('demo-response-poster', 'demo-task-poster', 'expert-student', 'Эксперт Тестовый', 'leader'),
      ],
    }),
    buildResponse({
      id: 'demo-response-archive',
      taskId: 'demo-task-archive',
      studentId: 'sp-demo-gleb',
      studentName: 'Куропатов Глеб',
      status: 'completed',
      coverLetter: 'Соберём архив командой: я на бэкенде, Алина на вёрстке.',
      submissionLink: 'https://demo.stud-pod.local/arxiv-gazety',
      reviewComment: 'Отличная работа всей команды: поиск по годам работает, адаптив аккуратный. Начислено 140 баллов.',
      createdAt: daysAgo(24),
      updatedAt: daysAgo(2),
      teamMembers: [
        buildMember('demo-response-archive', 'demo-task-archive', 'sp-demo-gleb', 'Куропатов Глеб', 'leader'),
        buildMember('demo-response-archive', 'demo-task-archive', 'sp-demo-alina', 'Яруллина Алина', 'member'),
        buildMember('demo-response-archive', 'demo-task-archive', 'expert-student', 'Эксперт Тестовый', 'member'),
      ],
    }),
  ],
  events: [
    {
      id: 'demo-event-upcoming',
      title: 'Проектная сессия: разбор задач осенней волны',
      description: 'Очная встреча участников и учреждений: разбор выполненных задач, планирование новых и нетворкинг.',
      organizationId: 'expert-organization',
      organizationName: ORG_NAME,
      date: daysFromNow(9),
      location: 'МЦ «Высота», Нижний Новгород',
      pointsReward: 20,
      registrationsCount: 12,
      createdAt: daysAgo(10),
    },
    {
      id: 'demo-event-past',
      title: 'Итоговая сессия пилота',
      description: 'Разбор результатов летнего пилота: 12 выполненных задач, карточки кейсов и награждение самых активных участников.',
      organizationId: 'expert-organization',
      organizationName: ORG_NAME,
      date: daysAgo(14),
      location: 'МЦ «Высота», Нижний Новгород',
      pointsReward: 20,
      registrationsCount: 17,
      createdAt: daysAgo(40),
    },
  ],
  eventRegistrations: [
    { id: 'demo-event-reg-1', eventId: 'demo-event-upcoming', studentId: 'sp-demo-gleb', createdAt: daysAgo(5) },
    { id: 'demo-event-reg-2', eventId: 'demo-event-upcoming', studentId: 'sp-demo-alina', createdAt: daysAgo(4) },
  ],
  products: [
    {
      id: 'demo-product-merch',
      title: 'Комплект мерча Университета Неймарк',
      description: 'Худи и футболка Университета Неймарк — награда для самых активных участников.',
      price: 1200,
      imageUrl: '/rewards/neimark-merch-2026.webp',
      category: 'Мерч',
      stock: 5,
      createdAt: daysAgo(30),
    },
    {
      id: 'demo-product-course',
      title: 'Сертификат на онлайн-курс по веб-дизайну',
      description: 'Сертификат на базовый курс по веб-дизайну от партнёров платформы.',
      price: 400,
      category: 'Обучение',
      stock: 10,
      createdAt: daysAgo(30),
    },
  ],
  purchases: [
    {
      id: 'demo-purchase-merch',
      productId: 'demo-product-merch',
      studentId: 'sp-demo-gleb',
      price: 1200,
      status: 'fulfilled',
      createdAt: daysAgo(7),
    },
  ],
  notifications: [
    {
      id: 'demo-notification-points',
      userId: 'expert-student',
      title: 'Задача принята: +105 баллов',
      message: 'Учреждение приняло афишу летней программы чтения. Баллы зачислены, кейс добавлен в портфолио.',
      read: false,
      createdAt: daysAgo(4),
      link: '/портфолио',
      type: 'success',
    },
    {
      id: 'demo-notification-new-task',
      userId: 'expert-student',
      title: 'Новая задача для отклика',
      message: 'Опубликован анонс фестиваля «Лето в парке» — 85 баллов. Успейте откликнуться первым.',
      read: false,
      createdAt: daysAgo(3),
      link: '/задачи/demo-task-announce',
      type: 'info',
    },
    {
      id: 'demo-notification-event',
      userId: 'expert-student',
      title: 'Проектная сессия через 9 дней',
      message: 'Разбор задач осенней волны в МЦ «Высота». Участие — 20 баллов.',
      read: false,
      createdAt: daysAgo(2),
      link: '/мероприятия',
      type: 'info',
    },
  ],
  studentsDirectory: [
    {
      id: 'sp-demo-gleb',
      name: 'Куропатов Глеб',
      university: 'Университет Неймарк',
      course: 3,
      description: 'Веб-разработка, опыт с цифровыми архивами и вёрсткой.',
      skills: ['Веб-разработка', 'HTML/CSS', 'JavaScript'],
      points: 360,
      completedTasksCount: 3,
      createdAt: daysAgo(60),
    },
    {
      id: 'sp-demo-magomed',
      name: 'Гаджиев Магомедрасул',
      university: 'Университет Неймарк',
      course: 3,
      description: 'Фулстек-разработка, участвовала в трёх задачах пилота.',
      skills: ['Веб-разработка', 'Дизайн'],
      points: 355,
      completedTasksCount: 3,
      createdAt: daysAgo(60),
    },
    {
      id: 'sp-demo-alina',
      name: 'Яруллина Алина',
      university: 'НГТУ им. Р.Е. Алексеева',
      course: 2,
      description: 'Дизайн интерфейсов и графики, работает в Figma.',
      skills: ['Дизайн', 'Figma', 'Афиши'],
      points: 190,
      completedTasksCount: 2,
      createdAt: daysAgo(58),
    },
    {
      id: 'sp-demo-viktoria',
      name: 'Пак Виктория',
      university: 'ННГУ им. Н.И. Лобачевского',
      course: 1,
      description: 'Тексты и соцсети, быстрые дедлайны.',
      skills: ['Копирайтинг', 'SMM'],
      points: 125,
      completedTasksCount: 1,
      createdAt: daysAgo(55),
    },
  ],
  platformStats: {
    totalStudents: 64,
    totalOrganizations: 5,
    activeTasks: 3,
    completedTasks: 2,
    totalResponses: 4,
    totalPointsAwarded: 1150,
  },
  evidenceStats: {
    registeredParticipants: 64,
    participatingOrganizations: 5,
    publishedTasks: 12,
    completedTasks: 12,
    offlineEvents: 3,
  },
  rewardWinners: [
    {
      productId: 'demo-product-merch',
      productTitle: 'Комплект мерча Университета Неймарк',
      productImageUrl: '/rewards/neimark-merch-2026.webp',
      studentName: 'Куропатов Глеб',
      price: 1200,
      awardedAt: daysAgo(7),
    },
  ],
});
