# Память для компиляции
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Кэш конфигурации ускоряет повторные сборки
org.gradle.configuration-cache=true

# Не тащим транзитивные зависимости из неожиданных мест
android.nonTransitiveRClass=true

# KSP
ksp.useKSP2=false
